/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projet_pfe;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JSpinner;
import javax.swing.*;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.text.PlainDocument;



/**
 *
 * @author mouna
 */
public class Link_budget_calculator_for_5G_NR extends javax.swing.JFrame {
 
    /**
     * Creates new form Throughput_calculator_5G_NR
     */
    public Link_budget_calculator_for_5G_NR() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        input_PRB = new javax.swing.JSpinner();
        UL = new javax.swing.JRadioButton();
        subcarrierspacing0 = new javax.swing.JRadioButton();
        DL = new javax.swing.JRadioButton();
        subcarrierspacing4 = new javax.swing.JRadioButton();
        subcarrierspacing2 = new javax.swing.JRadioButton();
        subcarrierspacing1 = new javax.swing.JRadioButton();
        subcarrierspacing3 = new javax.swing.JRadioButton();
        jLabel99 = new javax.swing.JLabel();
        entrer1 = new javax.swing.JButton();
        jLabel100 = new javax.swing.JLabel();
        output_subcarrier_quantity = new javax.swing.JTextField();
        distance = new javax.swing.JTextField();
        frequence = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        transmitPowerUt = new javax.swing.JTextField();
        cableLossUt = new javax.swing.JTextField();
        antennaGainUt = new javax.swing.JTextField();
        antennaHeightUt = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jSpinnerSINR = new javax.swing.JSpinner();
        jSpinnerNoise = new javax.swing.JSpinner();
        cableLossGN = new javax.swing.JSpinner();
        antennaGainGN = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jLabel130 = new javax.swing.JLabel();
        entrer3 = new javax.swing.JButton();
        jLabel131 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel134 = new javax.swing.JLabel();
        jTextFieldThermalnoise = new javax.swing.JTextField();
        jTextFieldResult = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jLabel133 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldBodyLoss = new javax.swing.JTextField();
        jTextFieldSlowFadingMargin = new javax.swing.JTextField();
        jTextFieldFoliageLoss = new javax.swing.JTextField();
        jTextFieldRain = new javax.swing.JTextField();
        jTextFieldInterferenceMargin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel126 = new javax.swing.JLabel();
        txt_password44 = new javax.swing.JPasswordField();
        jLabel127 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        get_result2 = new javax.swing.JButton();
        Propagation_model_path_loss1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel113 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jTextFieldFullPathLoss1 = new javax.swing.JTextField();
        LinkBudget1 = new javax.swing.JTextField();
        jTextFieldStatus1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "5G NR LINK BUDGET CALCULATOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jTabbedPane3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel95.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel95.setText("frequency for Tx (Mhz) :");

        jLabel96.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel96.setText("Number of PRB :");

        jLabel98.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel98.setText("Numerology - Subcarrier Spacing (µ)");

        jLabel101.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel101.setText("Direction of Link :");

        input_PRB.setValue(1);

        UL.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        UL.setSelected(true);
        UL.setText("UL (uplink)");

        subcarrierspacing0.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        subcarrierspacing0.setText("0: µ:15kHz");

        DL.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        DL.setText("DL (downlink)");

        subcarrierspacing4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        subcarrierspacing4.setText("4: µ:240kHz");

        subcarrierspacing2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        subcarrierspacing2.setText("2: µ:60kHz");

        subcarrierspacing1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        subcarrierspacing1.setSelected(true);
        subcarrierspacing1.setText("1: µ:30kHz");

        subcarrierspacing3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        subcarrierspacing3.setText("3: µ:120kHz");

        jLabel99.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel99.setText("Cell Radius (m) :");

        entrer1.setFont(new java.awt.Font("Segoe Script", 0, 10)); // NOI18N
        entrer1.setForeground(new java.awt.Color(102, 102, 102));
        entrer1.setText("Get result");
        entrer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrer1ActionPerformed(evt);
            }
        });

        jLabel100.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel100.setText("==> Subcarrier Quantity :");

        output_subcarrier_quantity.setEditable(false);
        output_subcarrier_quantity.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        output_subcarrier_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                output_subcarrier_quantityActionPerformed(evt);
            }
        });

        distance.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        distance.setText("700");
        distance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distanceActionPerformed(evt);
            }
        });
        distance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                distanceKeyPressed(evt);
            }
        });

        frequence.setForeground(new java.awt.Color(153, 153, 153));
        frequence.setText(" Support 0.5 To 100 GHz");
        frequence.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                frequenceFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                frequenceFocusLost(evt);
            }
        });
        frequence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequenceActionPerformed(evt);
            }
        });
        frequence.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                frequenceKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\input data prime .png")); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel99)
                            .addComponent(jLabel95))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(distance, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(frequence))
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(subcarrierspacing3)
                                                .addGap(18, 18, 18)
                                                .addComponent(subcarrierspacing4))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel16Layout.createSequentialGroup()
                                                .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(output_subcarrier_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel16Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(subcarrierspacing0)
                                        .addGap(18, 18, 18)
                                        .addComponent(subcarrierspacing1)
                                        .addGap(18, 18, 18)
                                        .addComponent(subcarrierspacing2)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                .addComponent(jLabel98)
                                .addGap(91, 91, 91))))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(input_PRB, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(DL)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(UL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(entrer1)
                        .addGap(182, 182, 182))))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel98)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subcarrierspacing0)
                            .addComponent(subcarrierspacing1)
                            .addComponent(subcarrierspacing2))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subcarrierspacing4)
                            .addComponent(subcarrierspacing3))
                        .addGap(47, 47, 47))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel99)
                            .addComponent(distance, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel95)
                            .addComponent(frequence, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel100, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel101)
                        .addComponent(DL)
                        .addComponent(output_subcarrier_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(UL)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(input_PRB, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel96)))
                    .addComponent(entrer1)
                    .addComponent(jLabel1))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Input data", jPanel15);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jLabel104.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel104.setText("Transmit power UT (dBm) :");

        jLabel105.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel105.setText("Antenna gain (dB) :");

        jLabel108.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel108.setText("Cable Loss (dB) :");

        jLabel106.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel106.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\UTT.jpg")); // NOI18N

        jLabel119.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel119.setText("Antenna Height (m) :");

        transmitPowerUt.setText("23");
        transmitPowerUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmitPowerUtActionPerformed(evt);
            }
        });
        transmitPowerUt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                transmitPowerUtKeyPressed(evt);
            }
        });

        cableLossUt.setText("0");
        cableLossUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cableLossUtActionPerformed(evt);
            }
        });
        cableLossUt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cableLossUtKeyPressed(evt);
            }
        });

        antennaGainUt.setText("0");
        antennaGainUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antennaGainUtActionPerformed(evt);
            }
        });
        antennaGainUt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                antennaGainUtKeyPressed(evt);
            }
        });

        antennaHeightUt.setText("1.5");
        antennaHeightUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antennaHeightUtActionPerformed(evt);
            }
        });
        antennaHeightUt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                antennaHeightUtKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(0, 78, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel105)
                    .addComponent(jLabel119))
                .addGap(60, 60, 60)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(antennaGainUt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cableLossUt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(antennaHeightUt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel104)
                .addGap(26, 26, 26)
                .addComponent(transmitPowerUt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel104)
                    .addComponent(transmitPowerUt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel108)
                            .addComponent(cableLossUt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel105)
                            .addComponent(antennaGainUt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel119)
                            .addComponent(antennaHeightUt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("UT configuration", jPanel17);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel109.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel109.setText("Cable Loss (dB) :");

        jLabel110.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel110.setText("Noise figure (dB) :");

        jLabel111.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel111.setText("Antenna gain (dB) :");

        jLabel115.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel115.setText("Target SINR :");

        jLabel120.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel120.setText("Antenna Height (m) :");

        jSpinnerSINR.setValue(-6);
        jSpinnerSINR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jSpinnerSINRKeyPressed(evt);
            }
        });

        jSpinnerNoise.setValue(5);

        cableLossGN.setValue(2);

        antennaGainGN.setValue(3);

        jSpinner7.setValue(23);

        jLabel130.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel130.setText("==> Receiver sensitivity (dBm) : ");

        entrer3.setFont(new java.awt.Font("Segoe Script", 0, 10)); // NOI18N
        entrer3.setForeground(new java.awt.Color(102, 102, 102));
        entrer3.setText("Get result");
        entrer3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrer3ActionPerformed(evt);
            }
        });

        jLabel131.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel131.setText("Bandwidth (hz) :");

        jTextField2.setEditable(false);

        jLabel134.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel134.setText("Thermal noise :");

        jTextFieldThermalnoise.setEditable(false);

        jTextFieldResult.setEditable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\gnode b.png")); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel110)
                                    .addComponent(jLabel109)
                                    .addComponent(jLabel115, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel20Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jSpinnerSINR, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSpinnerNoise, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cableLossGN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                    .addComponent(jLabel111)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(antennaGainGN, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(entrer3)
                                        .addComponent(jLabel120))
                                    .addGap(34, 34, 34)
                                    .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(222, 222, 222)
                        .addComponent(jLabel2)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel130, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                .addComponent(jLabel134, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                                .addComponent(jLabel131, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldThermalnoise, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel131, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel115)
                                .addComponent(jSpinnerSINR, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel134)
                                    .addComponent(jTextFieldThermalnoise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel130)))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jSpinnerNoise, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel110))))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cableLossGN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel109)))
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(antennaGainGN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel111))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinner7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel120))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entrer3)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47))))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("gNodeB Configuration", jPanel19);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        jLabel133.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel133.setText("Body loss (dB) :");

        jLabel138.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel138.setText("Slow fading margin (dB) :");

        jLabel139.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel139.setText("Foliage loss (dB) :");

        jLabel140.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel140.setText("Rain/Ice margin (dB) :");

        jLabel141.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel141.setText("Type of coverage  :");

        jLabel142.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel142.setText("Interference margin (dB) :");

        jComboBox2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Outdoor", " " }));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\mm1.jpg")); // NOI18N

        jTextFieldBodyLoss.setText("3");
        jTextFieldBodyLoss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBodyLossActionPerformed(evt);
            }
        });
        jTextFieldBodyLoss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBodyLossKeyPressed(evt);
            }
        });

        jTextFieldSlowFadingMargin.setText("7");

        jTextFieldFoliageLoss.setText("8.5");

        jTextFieldRain.setText("0");
        jTextFieldRain.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRainKeyPressed(evt);
            }
        });

        jTextFieldInterferenceMargin.setText("2");
        jTextFieldInterferenceMargin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInterferenceMarginActionPerformed(evt);
            }
        });
        jTextFieldInterferenceMargin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldInterferenceMarginKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel141, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel140, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldRain, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel138, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel133, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel139)
                                        .addGap(41, 41, 41))))
                            .addComponent(jLabel142, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldInterferenceMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldBodyLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldSlowFadingMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldFoliageLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(43, 43, 43))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel133)
                            .addComponent(jTextFieldBodyLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel138)
                            .addComponent(jTextFieldSlowFadingMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel139)
                            .addComponent(jTextFieldFoliageLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel140)
                            .addComponent(jTextFieldRain, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldInterferenceMargin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel142))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel141))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Additional losses", jPanel23);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        jLabel126.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel126.setText("5G Propagation Model (3GPP 38.901): ");

        txt_password44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password44ActionPerformed(evt);
            }
        });

        jLabel127.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel127.setText("Db");

        jLabel129.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\path loss 1.png")); // NOI18N

        jLabel132.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel132.setText("Propagation model Path loss [dB] :");

        get_result2.setFont(new java.awt.Font("Segoe Script", 0, 10)); // NOI18N
        get_result2.setForeground(new java.awt.Color(102, 102, 102));
        get_result2.setText("Get result");
        get_result2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_result2ActionPerformed(evt);
            }
        });

        Propagation_model_path_loss1.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jLabel5.setText("Free Space path Loss (FSPL)");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel126))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111)
                                .addComponent(get_result2)))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(Propagation_model_path_loss1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(577, 577, 577)
                                .addComponent(txt_password44, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel127, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel24Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel132))))
                    .addGroup(jPanel24Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel129, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Propagation_model_path_loss1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_result2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel129, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel126, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel127))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1527, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Path loss Calculation", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel113.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel113.setText("Signal level at receiver (Link Budget) (dBm) :");

        jLabel117.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel117.setText("Radio Channel Status");

        jLabel118.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel118.setText("Full Path loss (dB) :");

        jLabel135.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel135.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\result 1.png")); // NOI18N

        jTextFieldFullPathLoss1.setEditable(false);

        LinkBudget1.setEditable(false);

        jTextFieldStatus1.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel135, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel118)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldFullPathLoss1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel113)))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(LinkBudget1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel117)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(jLabel135, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFullPathLoss1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel118)
                    .addComponent(jLabel117)
                    .addComponent(jTextFieldStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel113)
                    .addComponent(LinkBudget1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane3.addTab("Result", jPanel3);

        jPanel8.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 942, -1));

        jButton1.setText("Let's calculate the Throughput 5G NR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 570, -1, -1));

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\200.png")); // NOI18N
        jPanel8.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
private void acceptNumbersOnly(JTextField textField) {
  
    textField.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c = e.getKeyChar();
            //if (!(Character.isDigit(c) || c == '.')) {
               // e.consume();
             if (!(Character.isDigit(c) || c == '.' || c == ',')) {
                e.consume();
            }
            // Replace ',' with '.' for decimal input
            if (c == ',') {
                e.setKeyChar('.');
            }
            
        }
    });
}

    
    
    private void entrer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrer1ActionPerformed
        // TODO add your handling code here:
int subcarrierQuantity;
int numberOfUsedRB = (int) input_PRB.getValue();
int subcarrierPerRB = 12;
        if(numberOfUsedRB==0 || numberOfUsedRB==1){

            subcarrierQuantity = numberOfUsedRB * subcarrierPerRB;
            output_subcarrier_quantity.setText(Integer.toString(subcarrierQuantity));


        }else{
            String errorMessage = " Error! ";
            output_subcarrier_quantity.setText(errorMessage);
        }


    }//GEN-LAST:event_entrer1ActionPerformed

    private void distanceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_distanceKeyPressed
        // TODO add your handling code here:
        acceptNumbersOnly(distance);
    }//GEN-LAST:event_distanceKeyPressed

    private void frequenceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_frequenceKeyPressed
        // TODO add your handling code here:
        acceptNumbersOnly(frequence);
     

     

      
 


    }//GEN-LAST:event_frequenceKeyPressed

    private void transmitPowerUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmitPowerUtActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_transmitPowerUtActionPerformed

    private void cableLossUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cableLossUtActionPerformed
        // TODO add your handling code here:    
        
    }//GEN-LAST:event_cableLossUtActionPerformed

    private void antennaGainUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antennaGainUtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_antennaGainUtActionPerformed

    private void antennaHeightUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antennaHeightUtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_antennaHeightUtActionPerformed

    private void transmitPowerUtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transmitPowerUtKeyPressed
acceptNumbersOnly(transmitPowerUt);   
    }//GEN-LAST:event_transmitPowerUtKeyPressed

    private void cableLossUtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cableLossUtKeyPressed
        acceptNumbersOnly(cableLossUt);
    }//GEN-LAST:event_cableLossUtKeyPressed

    private void antennaGainUtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_antennaGainUtKeyPressed
        // TODO add your handling code here:
        acceptNumbersOnly(antennaGainUt);
    }//GEN-LAST:event_antennaGainUtKeyPressed

    private void antennaHeightUtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_antennaHeightUtKeyPressed
        // TODO add your handling code here:
        acceptNumbersOnly(antennaHeightUt);
    }//GEN-LAST:event_antennaHeightUtKeyPressed

    private void output_subcarrier_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_output_subcarrier_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_output_subcarrier_quantityActionPerformed

    private void entrer3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrer3ActionPerformed
       // Receiver sensitivity (dBm) = Noise figure (dB) + Thermal noise (dBm) + SINR (dB)
        //Thermal noise =-174+10log("bandwidth" Hz)
        //PRB Bandwidth =12*lamdavaleur
      //  int subcarrierQuantity;
      double lambdaValue = 0.0;
       

            if (subcarrierspacing0.isSelected()) {
                lambdaValue = 15.0;
            } else if (subcarrierspacing1.isSelected()) {
               lambdaValue = 30.0;
            } else if (subcarrierspacing2.isSelected()) {
               lambdaValue = 60.0;
           } else if (subcarrierspacing3.isSelected()) {
                lambdaValue = 120.0;
           } else if (subcarrierspacing4.isSelected()) {
                lambdaValue = 240.0;
           }

            double prbBandwidth = 12.0 * lambdaValue;
            jTextField2.setText(String.format("%.2f kHz", prbBandwidth));
            double thermalNoise = -174 + 10 * Math.log10(prbBandwidth * 1000);
            // Afficher le bruit thermique dans le JTextField
         jTextFieldThermalnoise.setText(String.format("%.2f", thermalNoise));
         
            int noiseFigure = (int) jSpinnerNoise.getValue(); // Récupérer la valeur de la figure de bruit
             int sinr = (int) jSpinnerSINR.getValue(); // Récupérer la valeur de SINR
             double receiverSensitivity = noiseFigure + thermalNoise + sinr;

             // Afficher la sensibilité du récepteur dans le JTextField
             jTextFieldResult.setText(String.format("%.2f dB ", receiverSensitivity));
             jTextFieldResult.repaint(); 


  
 

    }//GEN-LAST:event_entrer3ActionPerformed

    private void jTextFieldBodyLossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBodyLossActionPerformed
        // TODO add your handling code here:
 


    }//GEN-LAST:event_jTextFieldBodyLossActionPerformed

    private void jTextFieldBodyLossKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBodyLossKeyPressed
        // TODO add your handling code here:
      acceptNumbersOnly(jTextFieldBodyLoss);
       ((AbstractDocument) jTextFieldBodyLoss.getDocument()).setDocumentFilter(new DocumentFilter() {
        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(string);
            builder.deleteCharAt(offset);
            builder.insert(offset, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.insertString(fb, offset, string, attr);
            }
        }

        public void replace(FilterBypass fb, int offset, int length, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(fb.getDocument().getText(0, fb.getDocument().getLength()));
            builder.replace(offset, offset + length, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.replace(fb, offset, length, string, attr);
            }
        }
        
        private boolean isValid(String text) {
            try {
                int num = Integer.parseInt(text);
                return (num >= 2 && num <= 5) || (num >= 8 && num <= 40) ;
               
                
            } catch (NumberFormatException e) {
                return false;
            }
        }
     

    });
         

    }//GEN-LAST:event_jTextFieldBodyLossKeyPressed

    private void jTextFieldRainKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRainKeyPressed
       acceptNumbersOnly(jTextFieldRain);
       ((AbstractDocument) jTextFieldRain.getDocument()).setDocumentFilter(new DocumentFilter() {
        public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(string);
            builder.deleteCharAt(offset);
            builder.insert(offset, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.insertString(fb, offset, string, attr);
            }
        }

        public void replace(FilterBypass fb, int offset, int length, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(fb.getDocument().getText(0, fb.getDocument().getLength()));
            builder.replace(offset, offset + length, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.replace(fb, offset, length, string, attr);
            }
        }
        
        private boolean isValid(String text) {
    try {
        int num = Integer.parseInt(text);
        return (num == 0) || (num == 3);
    } catch (NumberFormatException e) {
        return false;
    }
}

        
     

      });
    }//GEN-LAST:event_jTextFieldRainKeyPressed

    private void jTextFieldInterferenceMarginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInterferenceMarginKeyPressed
        // TODO add your handling code here:
         acceptNumbersOnly(jTextFieldInterferenceMargin);
       ((AbstractDocument) jTextFieldInterferenceMargin.getDocument()).setDocumentFilter(new DocumentFilter() {
        public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(string);
            builder.deleteCharAt(offset);
            builder.insert(offset, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.insertString(fb, offset, string, attr);
            }
        }

        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(fb.getDocument().getText(0, fb.getDocument().getLength()));
            builder.replace(offset, offset + length, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.replace(fb, offset, length, string, attr);
            }
        }
        
       private boolean isValid(String text) {
    try {
                int num = Integer.parseInt(text);
                if (DL.isSelected()) {
            double numDL = Double.parseDouble(text);
            return (numDL == 1) || (numDL == 6);
        } else if (UL.isSelected()) {
           
   
    double numUL = Double.parseDouble(text.replaceAll(",", "."));

    return  (numUL == 2) ;
} else {
    return false;
}


        
    } catch (NumberFormatException e) {
        return false;
    }
    
    //return false; // Return false if neither radio button is selected
}

        
     

      });
    }//GEN-LAST:event_jTextFieldInterferenceMarginKeyPressed

    private void jTextFieldInterferenceMarginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInterferenceMarginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInterferenceMarginActionPerformed
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.dispose();
                new Throughput_calculator_5G_NR().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
                new login_from().show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void distanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distanceActionPerformed
    

// Ajouter freqField à votre interface utilisateur

    }//GEN-LAST:event_distanceActionPerformed

    private void frequenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frequenceActionPerformed

    private void frequenceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_frequenceFocusGained
        // TODO add your handling code here:
        
        if(frequence.getText().equals(" Support 0.5 To 100 GHz"))
        {
            frequence.setText("");
            frequence.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_frequenceFocusGained

    private void frequenceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_frequenceFocusLost
        // TODO add your handling code here:
         if(frequence.getText().equals(""))
        {
            frequence.setText(" Support 0.5 To 100 GHz");
            frequence.setForeground(new Color(153,153,153));
            
        }
      
    }//GEN-LAST:event_frequenceFocusLost

    private void txt_password44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password44ActionPerformed

    private void get_result2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_result2ActionPerformed
        // calculer  Propagation_model_path_loss :
     //get value of distance
     double d = Double.parseDouble(distance.getText());   
      //get value of frequency
     double f = Double.parseDouble(frequence.getText()); 
     // Calculer le FSPL en utilisant la formule donnée
        double fspl = 20 * Math.log10(d) + 20 * Math.log10(f) - 27.55;
        // Afficher le résultat
        Propagation_model_path_loss1.setText(String.format("%.2f dB ", fspl));
        
        
        
         // calculer  Full_path_loss :
     //get value of BodyLoss
     double BodyLoss = Double.parseDouble(jTextFieldBodyLoss.getText());   
      //get value of FoliageLoss
     double FoliageLoss = Double.parseDouble(jTextFieldFoliageLoss.getText()); 
     //get value of SlowFadingMargin
     double SlowFadingMargin = Double.parseDouble(jTextFieldSlowFadingMargin.getText());   
      //get value of Rain
     double Rain = Double.parseDouble(jTextFieldRain.getText()); 
       //get value of InterferenceMargin
     double InterferenceMargin = Double.parseDouble(jTextFieldInterferenceMargin.getText()); 
     // Calculer le Full_path_loss en utilisant la formule donnée
        double full_path_loss =InterferenceMargin+Rain+SlowFadingMargin+FoliageLoss+BodyLoss+fspl ;
        // Afficher le résultat
        jTextFieldFullPathLoss1.setText(String.format("%.2f dB ", full_path_loss));
        
         // calculer  link budget :
     //get value of Transmit power from user terminal
     double transmitPower = Double.parseDouble(transmitPowerUt.getText());   
      //get value of antennaGain from user terminal
     double antennaGain1 = Double.parseDouble(antennaGainUt.getText()); 
     //get value of cableLoss from user terminal
     double cableLoss1 = Double.parseDouble(cableLossUt.getText());   
     
     //get value of Transmit power from gNodeB
     int antennaGain2 = (int) antennaGainGN.getValue();
     int cableLoss2 = (int) cableLossGN.getValue();
     
     
      
     
     
     // Calculer link budget en utilisant la formule donnée
        double link_bugdet =transmitPower+antennaGain1-cableLoss1+antennaGain2-cableLoss2-full_path_loss ;
        // Afficher le résultat
        LinkBudget1.setText(String.format("%.2f dB ", link_bugdet));
        
        

  // Model status
       int Input_PRB = (int) input_PRB.getValue();
      double link_budget_abs = Math.abs(link_bugdet);
              
if (Input_PRB == 0 && link_budget_abs <= 119.44) {
   jTextFieldStatus1.setText("fail");
   
} else if (Input_PRB == 1 && link_budget_abs >= 119.45) {
    jTextFieldStatus1.setText("fail");
    
} else if (Input_PRB == 1 && link_budget_abs <= 119.44) {
      jTextFieldStatus1.setText("pass");
     
}


    }//GEN-LAST:event_get_result2ActionPerformed

    private void jSpinnerSINRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jSpinnerSINRKeyPressed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jSpinnerSINRKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Link_budget_calculator_for_5G_NR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Link_budget_calculator_for_5G_NR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Link_budget_calculator_for_5G_NR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Link_budget_calculator_for_5G_NR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Link_budget_calculator_for_5G_NR().setVisible(true);
            }
        });
        

}

        
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton DL;
    private javax.swing.JTextField LinkBudget1;
    private javax.swing.JTextField Propagation_model_path_loss1;
    private javax.swing.JRadioButton UL;
    private javax.swing.JSpinner antennaGainGN;
    private javax.swing.JTextField antennaGainUt;
    private javax.swing.JTextField antennaHeightUt;
    private javax.swing.JSpinner cableLossGN;
    private javax.swing.JTextField cableLossUt;
    private javax.swing.JTextField distance;
    private javax.swing.JButton entrer1;
    private javax.swing.JButton entrer3;
    private javax.swing.JTextField frequence;
    private javax.swing.JButton get_result2;
    private javax.swing.JSpinner input_PRB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinnerNoise;
    private javax.swing.JSpinner jSpinnerSINR;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldBodyLoss;
    private javax.swing.JTextField jTextFieldFoliageLoss;
    private javax.swing.JTextField jTextFieldFullPathLoss1;
    private javax.swing.JTextField jTextFieldInterferenceMargin;
    private javax.swing.JTextField jTextFieldRain;
    private javax.swing.JTextField jTextFieldResult;
    private javax.swing.JTextField jTextFieldSlowFadingMargin;
    private javax.swing.JTextField jTextFieldStatus1;
    private javax.swing.JTextField jTextFieldThermalnoise;
    private javax.swing.JTextField output_subcarrier_quantity;
    private javax.swing.JRadioButton subcarrierspacing0;
    private javax.swing.JRadioButton subcarrierspacing1;
    private javax.swing.JRadioButton subcarrierspacing2;
    private javax.swing.JRadioButton subcarrierspacing3;
    private javax.swing.JRadioButton subcarrierspacing4;
    private javax.swing.JTextField transmitPowerUt;
    private javax.swing.JPasswordField txt_password44;
    // End of variables declaration//GEN-END:variables
}
