/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projet_pfe;

import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author mouna
 */
public class Throughput_calculator_5G_NR extends javax.swing.JFrame {

    /**
     * Creates new form LinkBudgetCalculatorFor5GNR
     */
    public Throughput_calculator_5G_NR() {
        initComponents();
    }

    
    
    private void AcceptNumbersOnly(JTextField textField) {
  
    textField.addKeyListener(new KeyAdapter() {
        public void keyTyped(KeyEvent e) {
            char c = e.getKeyChar();
            //if (!(Character.isDigit(c) || c == '.')) {
               // e.consume();
             if (!(Character.isDigit(c) || c == '.' || c == ',')) {
                e.consume();
            }
            // Replace ',' with '.' for decimal input
            if (c == ',') {
                e.setKeyChar('.');
            }
            
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel97 = new javax.swing.JLabel();
        txt_password37 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel109 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        dl = new javax.swing.JRadioButton();
        ul = new javax.swing.JRadioButton();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jComboBoxQ = new javax.swing.JComboBox<>();
        jComboBoxF = new javax.swing.JComboBox<>();
        jLabel108 = new javax.swing.JLabel();
        j = new javax.swing.JTextField();
        v_de_j = new javax.swing.JTextField();
        BW = new javax.swing.JTextField();
        Rmax = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jLabel133 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jComboBoxOH = new javax.swing.JComboBox<>();
        jButton_get_result = new javax.swing.JButton();
        Nbw_PRB_j = new javax.swing.JTextField();
        Lamda = new javax.swing.JTextField();
        jLabel113 = new javax.swing.JLabel();
        T_lamda = new javax.swing.JTextField();
        mouna = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_register1 = new javax.swing.JButton();
        btn_register2 = new javax.swing.JButton();
        btn_register3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("5G NR LINK BUDGET CALCULATOR");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THROUGHPUT CALCULATOR 5G NR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Book Antiqua", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jTabbedPane3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));

        jLabel97.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel97.setText("==> Subcarrier Quantity :");

        txt_password37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password37ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Following fields are used in 5G NR throughput calculation:\n  * J : number of aggregated component carriers in a band or band combination\n  * Rmax : 948/1024\n  * Qm(j) : Maximum modulation order, Qm is 2 for QPSK, 4 for 16QAM, 6 for 32QAM, 8 for 256QAM\n  * f(j) : Scaling factor, can take any value from 1/0.8/0.75/0.4\n  * μ : 5G NR Numerology, can take any value from 0 to 5.\n  * Tsμ : Average OFDM symbol duration in a subframe for μ value,\n            •  Tsμ = 10-3/(14*2μ).\n   *NPRBBW(j),μ : Maximum RB Allocation in bandwidth, BW(j)with numerology (μ),\n             BW(j) is UE supported maximum Bandwidth in given band or in band combinations.\n             REs are grouped into PRBs (Physical Resource Blocks). Each PRB consists of 12 Subcarriers.\n    * OH(j) : Overhead which takes any of the following values.\n             • [0.14] → Frequency Range FR1 for DL\n             • [0.18] → Frequency Range FR2 for DL\n             • [0.08] → Frequency Range FR1 for UL\n             • [0.10] → Frequency Range FR2 for DL");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("The 5G NR Throughput Calculator is a tool used to estimate the maximum data transfer rate that can be achieved over a 5G network using the \nNew Radio (NR) technology.\n The throughput is calculated based on the 3GPP TS 38.306 standard where there is many several factors, including modulation , the channel \nbandwidth and number of layers used in the transmission.\n Approximately data transfer rate of 5G NR can be calculated using the formula:");
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel97)
                        .addGap(751, 751, 751)
                        .addComponent(txt_password37, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 918, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 905, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel97)
                    .addComponent(txt_password37, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 1005, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 455, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Lest know 5G NR Throughput calculator ", jPanel15);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel109.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel109.setText("v(j)Layers - maximum number of MIMO layers ");

        jLabel111.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N

        jLabel100.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel100.setText("Direction of data transfer");

        dl.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        dl.setSelected(true);
        dl.setText("DL (downlink)");
        dl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dlActionPerformed(evt);
            }
        });

        ul.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        ul.setText("UL (uplink)");

        jLabel103.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel103.setText("J - number of aggregated component carriers");

        jLabel104.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel104.setText(" Q(j)m");

        jLabel106.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel106.setText("Rmax( 948/1024 = 0.92578125)");

        jLabel107.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel107.setText("f(j) Scaling factor (3GPP 38.306)");

        jComboBoxQ.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBoxQ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "256QAM", "16QAM", "64QAM", "QPSK" }));

        jComboBoxF.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBoxF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0.8", "0.75", "0.4", "other" }));

        jLabel108.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel108.setText("BW(j)- band Bandwidth, MHz (3GPP 38.104)");

        j.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        j.setText("1");
        j.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jKeyPressed(evt);
            }
        });

        v_de_j.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        v_de_j.setText("4");
        v_de_j.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_de_jActionPerformed(evt);
            }
        });
        v_de_j.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                v_de_jKeyPressed(evt);
            }
        });

        BW.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        BW.setText("50");
        BW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BWActionPerformed(evt);
            }
        });
        BW.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BWKeyPressed(evt);
            }
        });

        Rmax.setFont(new java.awt.Font("Segoe Print", 0, 8)); // NOI18N
        Rmax.setForeground(new java.awt.Color(153, 153, 153));
        Rmax.setText("if you don't know what is it, don't change");
        Rmax.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RmaxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RmaxFocusLost(evt);
            }
        });
        Rmax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RmaxKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(ul, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel109)
                            .addComponent(jLabel103)))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(jLabel106)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Rmax, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel108))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxF, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(243, 243, 243)
                                .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxQ, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(j)
                    .addComponent(v_de_j)
                    .addComponent(BW, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(17, 26, Short.MAX_VALUE)
                .addComponent(jLabel111)
                .addGap(984, 984, 984))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel109)
                                    .addComponent(v_de_j, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxQ, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel104)
                                    .addComponent(jComboBoxF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel107))
                                .addGap(20, 20, 20)
                                .addComponent(BW, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel20Layout.createSequentialGroup()
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dl)
                                    .addComponent(jLabel100))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ul)
                                .addGap(121, 121, 121)
                                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel108)
                                    .addComponent(Rmax, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel106))))
                        .addGap(748, 748, 748))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel103)
                            .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(953, 953, 953)))
                .addComponent(jLabel111)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Input data", jPanel19);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));

        jLabel133.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel133.setText("FR(j) Frequency Range 3GPP 38.104:");

        jLabel139.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel139.setText("µ(j) -value of carrier configuration (3GPP 38.211) ");

        jLabel140.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel140.setText("DL and UL µ(j)");

        jLabel141.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(51, 0, 255));
        jLabel141.setText("Tμs(j) = (10^-3)/(14*2^μ)");

        jLabel142.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel142.setText("NbwPRB(j) for selected BW(j), FR(j), µ(j)");

        jComboBox2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "15kHz", "30kHz", "60kHz", "120kHz" }));

        jComboBox6.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FR1", "FR2" }));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\max.png")); // NOI18N

        jLabel114.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel114.setText("verhead OH(j) for control channels Mode");

        jComboBoxOH.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBoxOH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0.14", "0.18", "0.08", "0.10" }));

        jButton_get_result.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jButton_get_result.setForeground(new java.awt.Color(153, 153, 153));
        jButton_get_result.setText("Get Result");
        jButton_get_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_get_resultActionPerformed(evt);
            }
        });

        Nbw_PRB_j.setText("133");
        Nbw_PRB_j.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Nbw_PRB_jKeyPressed(evt);
            }
        });

        Lamda.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        Lamda.setText("1");
        Lamda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LamdaKeyPressed(evt);
            }
        });

        jLabel113.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel113.setForeground(new java.awt.Color(51, 0, 255));
        jLabel113.setText("Calculated 5G NR Throughput, Mbps");

        T_lamda.setEditable(false);
        T_lamda.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        mouna.setEditable(false);
        mouna.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel141)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(T_lamda, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32))
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                .addComponent(jLabel114, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jComboBoxOH, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                .addComponent(jLabel113)
                                                .addGap(18, 18, 18)
                                                .addComponent(mouna, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 36, Short.MAX_VALUE))))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel139)
                                .addGap(18, 18, 18)
                                .addComponent(Lamda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel142)
                                .addGap(29, 29, 29)
                                .addComponent(Nbw_PRB_j, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel133, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(557, 557, 557))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jButton_get_result)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel140)
                .addGap(50, 50, 50)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel139)
                            .addComponent(Lamda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel133)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)))
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(0, 288, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel113)
                            .addComponent(mouna, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel142)
                                    .addComponent(Nbw_PRB_j, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel140)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel114)
                                    .addComponent(jComboBoxOH, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel141, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(T_lamda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(20, 20, 20)
                        .addComponent(jButton_get_result)
                        .addGap(12, 12, 12)))
                .addGap(65, 65, 65))
        );

        jTabbedPane3.addTab("Result", jPanel23);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\mmm.png")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 0, 18)); // NOI18N
        jLabel11.setText("\n is an application developed by Kouki Mouna and Hedir Askri to calculate 5G NR Throughput and 5G NR Link budget ");

        jLabel12.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        jLabel12.setText("  \"Wireless Communication Tools for 5G Networks\" ");

        jLabel13.setFont(new java.awt.Font("Segoe Script", 0, 10)); // NOI18N
        jLabel13.setText("Verssion1.0");

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\issatm.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\Capture d’écran tt 161046.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 21, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)))
                        .addGap(61, 61, 61))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(404, 404, 404)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel13)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );

        jTabbedPane3.addTab("Abouat_Us", jPanel3);

        jPanel8.add(jTabbedPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1020, 550));

        btn_register.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btn_register.setText("Exit");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        jPanel8.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mouna\\Desktop\\image app\\200.png")); // NOI18N
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        btn_register1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btn_register1.setText("Next");
        btn_register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register1ActionPerformed(evt);
            }
        });
        jPanel8.add(btn_register1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 589, -1, 50));

        btn_register2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btn_register2.setText("Exit");
        btn_register2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register2ActionPerformed(evt);
            }
        });
        jPanel8.add(btn_register2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, -1, -1));

        btn_register3.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        btn_register3.setText("Exit");
        btn_register3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_register3ActionPerformed(evt);
            }
        });
        jPanel8.add(btn_register3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.getAccessibleContext().setAccessibleName("5G NR LINK BUDGET CALCULATOR");

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_password37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password37ActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        this.dispose();
        new login_from().show();
    }//GEN-LAST:event_btn_registerActionPerformed

    private void dlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dlActionPerformed

    private void jButton_get_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_get_resultActionPerformed
         // TODO add your handling code here:
        
     
            // Récupérer la valeur de lamda à partir de l'élément de texte Lamda
             double lamda = Double.parseDouble(Lamda.getText());

          // Calculer la valeur de Ts lamda à l'aide de la formule
double Ts = 0.001 / (14 * Math.pow(2, lamda));

// Afficher la valeur de Ts lamda dans l'élément de texte T_lamda avec une précision de 10 chiffres après la virgule décimale
T_lamda.setText(String.format("%.10f", Ts));


                      // extraire la chaîne sélectionnée du JComboBox
                      String selectedValue = (String) jComboBoxF.getSelectedItem();

                      // convertir la chaîne en double
                      double value = Double.parseDouble(selectedValue);

                      //get value of maximum number of mimo loyers 
                         double v = Double.parseDouble(v_de_j.getText());
                    //get value from jComboxQ (modulation order) 
                          String Q = (String) jComboBoxQ.getSelectedItem();
                   int valuee ;
                   if (Q.equals("QPSK")) {
                       valuee = 2;
                   } else if (Q.equals("16QAM")) {
                       valuee = 4;
                   } else if (Q.equals("64QAM")) {
                       valuee = 6;
                   } else {
                       valuee = 8;
                   }
                //get value from Rmax 
                              double Rmaax = Double.parseDouble(Rmax.getText());
                //get value from NBW-PRB of j
                               double Nbw_PRB_J = Double.parseDouble(Nbw_PRB_j.getText());
                //get value from jComboBoxF (oh ) 

                      String oh = (String) jComboBoxOH.getSelectedItem();
                  // convertir la chaîne en double
                                      double Oh = Double.parseDouble(oh);  
                                      
                    double cst1 = (Nbw_PRB_J * 12) / Ts ;
                    
                     double cst2 = (1-Oh) ;
                double valeurJ = Double.parseDouble(j.getText());  
                
  // calculer la throughput 
double throughputt = 0;
for (int i = 1;i <= valeurJ ; i++) {
    throughputt += v * valuee * value * Rmaax * cst1 * cst2 ;
}
throughputt *= 0.000001;

mouna.setText(String.format("%.10f",  throughputt));


// afficher la nouvelle valeur dans un JLabel
//mouna.setText(Double.toString(throughputt));

     
    }//GEN-LAST:event_jButton_get_resultActionPerformed

    private void RmaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RmaxKeyPressed
        // TODO add your handling code here:
        AcceptNumbersOnly(Rmax);
    }//GEN-LAST:event_RmaxKeyPressed

    private void jKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jKeyPressed
        // TODO add your handling code here:
         AcceptNumbersOnly(j);
         ((AbstractDocument) j.getDocument()).setDocumentFilter(new DocumentFilter() {
        public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(string);
            builder.deleteCharAt(offset);
            builder.insert(offset, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.insertString(fb, offset, string, attr);
            }
        }

        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(fb.getDocument().getText(0, fb.getDocument().getLength()));
            builder.replace(offset, offset + length, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.replace(fb, offset, length, string, attr);
            }
        }
        
        private boolean isValid(String text) {
            try {
                int Num = Integer.parseInt(text);
                return (Num >= 0 && Num <= 16)  ;
               
                
            } catch (NumberFormatException e) {
                return false;
            }
        }
     

    });
    }//GEN-LAST:event_jKeyPressed

    private void v_de_jKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_v_de_jKeyPressed
        // TODO add your handling code here:
         AcceptNumbersOnly(v_de_j);
         ((AbstractDocument) v_de_j.getDocument()).setDocumentFilter(new DocumentFilter() {
        public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(string);
            builder.deleteCharAt(offset);
            builder.insert(offset, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.insertString(fb, offset, string, attr);
            }
        }

        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(fb.getDocument().getText(0, fb.getDocument().getLength()));
            builder.replace(offset, offset + length, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.replace(fb, offset, length, string, attr);
            }
        }
         
        private boolean isValid(String text) {
            
    try {
        int numm = Integer.parseInt(text);
        if (dl.isSelected()) {
            return (numm <= 8) && (numm >= 0);
        } else if (ul.isSelected()) {
            return (numm <= 4) && (numm >= 0);
        }
    } catch (NumberFormatException e) {
        return false;
    }
    return false;
}

     

    });
    }//GEN-LAST:event_v_de_jKeyPressed

    private void BWKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BWKeyPressed
        // TODO add your handling code here:
         AcceptNumbersOnly(BW);
      
    }//GEN-LAST:event_BWKeyPressed

    private void LamdaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LamdaKeyPressed
        // TODO add your handling code here:
        AcceptNumbersOnly(Lamda);
        ((AbstractDocument) Lamda.getDocument()).setDocumentFilter(new DocumentFilter() {
        public void insertString(DocumentFilter.FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(string);
            builder.deleteCharAt(offset);
            builder.insert(offset, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.insertString(fb, offset, string, attr);
            }
        }
 
        public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String string, AttributeSet attr) throws BadLocationException {
            StringBuilder builder = new StringBuilder(fb.getDocument().getText(0, fb.getDocument().getLength()));
            builder.replace(offset, offset + length, string);
            String text = builder.toString();
            
            if (isValid(text)) {
                super.replace(fb, offset, length, string, attr);
            }
        }
        
        private boolean isValid(String text) {
            try {
                int Numr = Integer.parseInt(text);
                return (Numr >= 0 && Numr <=3)  ;
               
                
            } catch (NumberFormatException e) {
                return false;
            }
        }
     

    });
    }//GEN-LAST:event_LamdaKeyPressed

    private void Nbw_PRB_jKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Nbw_PRB_jKeyPressed
        // TODO add your handling code here:
        AcceptNumbersOnly(Nbw_PRB_j);
    }//GEN-LAST:event_Nbw_PRB_jKeyPressed

    private void v_de_jActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_de_jActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_de_jActionPerformed

    private void RmaxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RmaxFocusGained
        // TODO add your handling code here:
          
        if(Rmax.getText().equals("if you don't know what is it, don't change"))
        {
            Rmax.setText("");
            Rmax.setForeground(new Color(153,153,153));
            
        }
                                      

    }//GEN-LAST:event_RmaxFocusGained

    private void RmaxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RmaxFocusLost
        // TODO add your handling code here:
         if(Rmax.getText().equals(""))
        {
            Rmax.setText("if you don't know what is it, don't change");
            Rmax.setForeground(new Color(153,153,153));
            
        }
    }//GEN-LAST:event_RmaxFocusLost

    private void BWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BWActionPerformed

    private void btn_register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register1ActionPerformed
        this.dispose();
        new Link_budget_calculator_for_5G_NR().show();
    }//GEN-LAST:event_btn_register1ActionPerformed

    private void btn_register2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_register2ActionPerformed

    private void btn_register3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_register3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_register3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Throughput_calculator_5G_NR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Throughput_calculator_5G_NR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Throughput_calculator_5G_NR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Throughput_calculator_5G_NR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Throughput_calculator_5G_NR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BW;
    private javax.swing.JTextField Lamda;
    private javax.swing.JTextField Nbw_PRB_j;
    private javax.swing.JTextField Rmax;
    private javax.swing.JTextField T_lamda;
    private javax.swing.JButton btn_register;
    private javax.swing.JButton btn_register1;
    private javax.swing.JButton btn_register2;
    private javax.swing.JButton btn_register3;
    private javax.swing.JRadioButton dl;
    private javax.swing.JTextField j;
    private javax.swing.JButton jButton_get_result;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBoxF;
    private javax.swing.JComboBox<String> jComboBoxOH;
    private javax.swing.JComboBox<String> jComboBoxQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField mouna;
    private javax.swing.JPasswordField txt_password37;
    private javax.swing.JRadioButton ul;
    private javax.swing.JTextField v_de_j;
    // End of variables declaration//GEN-END:variables
}
